### ISSUE TITLE
Does not install azure cli

### ISSUE THREAD

**Issue by donmstewart** [deislabs/porter-arm#30]
The Mixin does not install the Azure CLI into the `innvocationImage`. The code seems to be commented out in `build.go`

**Comment by carolynvs** [comment]
That's correct. The az cli makes the invocation image a bit large (almost ~700MB) which is why we didn't want to include it in this mixin here.

I suggest you use https://porter.sh/mixins/az/. That is what we are replacing the `azure` mixin with.

We are still working on a plan for either deprecating or redoing the `azure` mixin in some way so that it is smaller and optimized for a single task.
